# Generated by Django 3.1.3 on 2020-11-30 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('slug', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=1000)),
                ('slug', models.CharField(max_length=256)),
                ('body', models.TextField(default='Body')),
                ('excerpt', models.TextField(default='Excerpt')),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft'), ('Deleted', 'Deleted')], default='Draft', max_length=16)),
                ('mod_date', models.DateTimeField(verbose_name='Date modified')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Product name', max_length=1000)),
                ('is_featured', models.BooleanField(default=True, help_text='Check if featured', verbose_name='Featured product?')),
                ('slug', models.CharField(default='slug', max_length=256)),
                ('description', models.TextField(default='Product description')),
                ('features', models.TextField(default='Product features')),
                ('image', models.ImageField(blank=True, upload_to='product/')),
                ('price', models.CharField(default='$20', max_length=16)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Deleted', 'Deleted')], default='Available', max_length=16)),
                ('mod_date', models.DateTimeField(verbose_name='Date modified')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.category')),
            ],
        ),
    ]
