# Generated by Django 3.1.3 on 2020-12-30 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=70)),
                ('website', models.URLField(blank=True, default='', null=True)),
                ('company', models.CharField(default='', max_length=200)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None)),
                ('unit', models.CharField(default='', max_length=100)),
                ('street_number', models.CharField(default='', max_length=50)),
                ('street_name', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('state', models.CharField(choices=[('Australia', (('A1', 'Australian Capital Territory'), ('A2', 'Northern Territory'), ('A3', 'State of New South Wales'), ('A4', 'State of Queensland'), ('A5', 'State of South Australia'), ('A6', 'State of Tasmania'), ('A7', 'State of Victoria'), ('A8', 'State of Western Australia'))), ('Bangladesh', (('B1', 'Barisal Division'), ('B2', 'Chittagong Division'), ('B3', 'Dhaka Division'), ('B4', 'Khulna Division'), ('B5', 'Mymensingh Division'), ('B6', 'Rajshahi Division'), ('B7', 'Rangpur Division'), ('B8', 'Sylhet Division'))), ('Canada', (('C1', 'Alberta'), ('C2', 'British Columbia'), ('C3', 'Manitoba'), ('C4', 'New Brunswick/Nouveau-Brunswick'), ('C5', 'Newfoundland and Labrador'), ('C6', 'Northwest Territories'), ('C7', 'Nova Scotia'), ('C8', 'Nunavut'), ('C9', 'Ontario'), ('C10', 'Prince Edward Island'), ('C11', 'Quebec'), ('C12', 'Saskatchewan'), ('C13', 'Yukon'))), ('USA', (('US1', 'Alabama'), ('US2', 'Alaska'), ('US3', 'Arizona'), ('US4', 'Arkansas'), ('US5', 'California'), ('US6', 'Colorado'), ('US7', 'Connecticut'), ('US8', 'Delaware'), ('US9', 'District of Columbia'), ('US10', 'Florida'), ('US11', 'Georgia'), ('US12', 'Hawaii'), ('US13', 'Idaho'), ('US14', 'Illinois'), ('US15', 'Indiana'), ('US16', 'Iowa'), ('US17', 'Kansas'), ('US18', 'Kentucky'), ('US19', 'Louisiana'), ('US20', 'Maine'), ('US21', 'Maryland'), ('US22', 'Massachusetts'), ('US23', 'Michigan'), ('US24', 'Minnesota'), ('US25', 'Mississippi'), ('US26', 'Missouri'), ('US27', 'Montana'), ('US28', 'Nebraska'), ('US29', 'Nevada'), ('US30', 'New Hampshire'), ('US31', 'New Jersey'), ('US32', 'New Mexico'), ('US33', 'New York'), ('US34', 'North Carolina'), ('US35', 'North Dakota'), ('US36', 'Ohio'), ('US37', 'Oklahoma'), ('US38', 'Oregon'), ('US39', 'Pennsylvania'), ('US40', 'Rhode Island'), ('US41', 'South Carolina'), ('US42', 'South Dakota'), ('US43', 'Tennessee'), ('US44', 'Texas'), ('US45', 'Utah'), ('US46', 'Vermont'), ('US47', 'Virginia'), ('US48', 'Washington'), ('US49', 'West Virginia'), ('US50', 'Wisconsin'), ('US51', 'Wyoming')))], max_length=50)),
                ('zip_code', models.CharField(default='', max_length=50)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
