# Generated by Django 3.1.2 on 2020-11-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(blank=True, db_column='temperature', default=0.0, null=True)),
                ('relative_humidity', models.FloatField(blank=True, db_column='relative_humidity', default=0.0, null=True)),
                ('barometric_pressure', models.FloatField(blank=True, db_column='barometric_pressure', default=0.0, null=True)),
                ('precipitation', models.FloatField(blank=True, db_column='precipitation', default=0.0, null=True)),
                ('incoming_solar_radiation', models.FloatField(blank=True, db_column='incoming_solar_radiation', default=0.0, null=True)),
                ('outgoing_solar_radiation', models.FloatField(blank=True, db_column='outgoing_solar_radiation', default=0.0, null=True)),
                ('wind_speed', models.FloatField(blank=True, db_column='wind_speed', default=0.0, null=True)),
                ('wind_direction', models.CharField(blank=True, db_column='wind_direction', max_length=255, null=True)),
                ('photosynthetically_active_radiation', models.FloatField(blank=True, db_column='photosynthetically_active_radiation', default=0.0, null=True)),
                ('captured_sensor_time_date', models.DateTimeField(db_column='captured_sensor_time_date', null=True)),
            ],
        ),
    ]
