# Generated by Django 3.1.3 on 2020-11-27 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='data',
            table='Graph_table',
        ),
    ]
